[package]
name = "dff"
description = "Duplicate File Finder"
version = "0.1.0"
authors = ["Piotr Kołaczkowski <pkolaczk@datastax.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jwalk = "0.5.1"
chashmap = "2.2.2"
rayon = "1.3.0"
structopt = "0.3"
