[package]
name = "dff"
description = "Duplicate File Finder"
version = "0.1.0"
authors = ["Piotr Kołaczkowski <pkolaczk@datastax.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atomic-counter = "1.0.1"
bytesize = "1.0.0"
dashmap = "3.11.1"
fasthash = "0.4.0"
indicatif = { version = "0.14.0", features = ["with_rayon"] }
jwalk = "0.5.1"
rayon = "1.3.0"
smallvec = "1.4.0"
structopt = "0.3"
