[package]
name = "fclones"
description = "File Clones Finder"
version = "0.1.0"
authors = ["Piotr Kołaczkowski <pkolaczk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atomic-counter = "1.0.1"
bytesize = "1.0.0"
clap = "2.33.0"
console = "0.11.2"
dashmap = "3.11.1"
fasthash = "0.4.0"
indicatif = { version = "0.14.0", features = ["with_rayon"] }
itertools = "0.9.0"
nom = "5.1.1"
pcre2 = { git = "https://github.com/pkolaczk/rust-pcre2.git" }
rayon = "1.3.0"
regex = "1.3.7"
smallvec = "1.4.0"
structopt = "0.3"
sys-info = "0.6.1"
thread_local = "1.0.1"

[target.'cfg(unix)'.dependencies]
nix = "0.17.0"
libc = "0.2.69"