version: 2.1

jobs:
  build:
    docker:
      - image: circleci/rust:latest

    steps:
      - checkout
      - run:
          name: Setup build environment
          command: |
            sudo apt-get update
            sudo apt-get install -y git
          no_output_timeout: 1800s
      - run:
          name: Format
          command: |
            rustup component add rustfmt
            cargo fmt --all -- --check
      - run:
          name: Clippy
          command: |
            rustup component add clippy
            cargo clippy --all -- -D warnings -D rust-2018-idioms
      - run:
          name: Test
          command: |
            export RUST_BACKTRACE=1
            cargo test

workflows:
  version: 2.1
  build:
    jobs:
      - build